"""Builds the Windows installer:  .venv\\Scripts\\python packaging\\build.py

1. renders the app icon to build/anihub.ico
2. PyInstaller, from a generated .spec, two executables sharing one runtime (no PySide6 duplicated) -> dist/AniHUB/
   - AniHUB.exe            the program
   - AniHUB Music.exe      the same program, opened straight on Anime > Music
3. Inno Setup -> dist/AniHUB-Setup-<version>.exe (both .exe get a Start Menu entry; the desktop icon is the main one)
"""
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

EXCLUDES = ["PySide6.QtWebEngineCore", "PySide6.QtWebEngineWidgets", "PySide6.QtWebEngineQuick", "PySide6.Qt3DCore",
            "PySide6.Qt3DRender", "PySide6.QtQuick", "PySide6.QtQml", "PySide6.QtCharts", "PySide6.QtDataVisualization",
            "PySide6.QtPdf", "PySide6.QtPdfWidgets", "PySide6.QtDesigner", "PySide6.QtSql", "PySide6.QtTest",
            "PySide6.QtBluetooth", "PySide6.QtNfc", "PySide6.QtSensors", "PySide6.QtSerialPort", "tkinter", "pytest"]

SPEC = """# Generated by packaging/build.py -- do not edit by hand.
# Two executables (AniHUB.exe, "AniHUB Music.exe") sharing one collected runtime: MERGE() lets the second Analysis reuse
# everything the first one already found, so the music launcher does not duplicate PySide6 and the rest of the bundle.
a_main = Analysis([{entry!r}], pathex=[{src!r}], datas=[({data!r}, 'anihub/data')],
                   hiddenimports={hidden!r}, excludes={excludes!r})
a_music = Analysis([{entry_music!r}], pathex=[{src!r}], excludes={excludes!r})
MERGE((a_main, 'entry', 'AniHUB'), (a_music, 'entry_music', 'AniHUB Music'))

pyz_main = PYZ(a_main.pure, a_main.zipped_data)
exe_main = EXE(pyz_main, a_main.scripts, [], exclude_binaries=True, name='AniHUB', icon={icon!r}, console=False)

pyz_music = PYZ(a_music.pure, a_music.zipped_data)
exe_music = EXE(pyz_music, a_music.scripts, [], exclude_binaries=True, name='AniHUB Music', icon={icon!r}, console=False)

COLLECT(exe_main, a_main.binaries, a_main.zipfiles, a_main.datas,
        exe_music, a_music.binaries, a_music.zipfiles, a_music.datas,
        strip=False, upx=False, name='AniHUB')
"""


def make_icon() -> Path:
    from PySide6.QtGui import QGuiApplication

    from anihub.ui.taskbar import ICON_SIZES, write_ico
    from anihub.ui.theme import make_app_icon

    app = QGuiApplication.instance() or QGuiApplication([])
    out = ROOT / "build" / "anihub.ico"
    out.parent.mkdir(exist_ok=True)
    icon = make_app_icon()
    write_ico([icon.pixmap(size, size) for size in ICON_SIZES], out)
    assert out.exists() and out.stat().st_size > 0, "icon was not written"
    return out


def find_iscc() -> str | None:
    found = shutil.which("ISCC")
    if found:
        return found
    for base in ("C:/Program Files (x86)/Inno Setup 6", "C:/Program Files/Inno Setup 6",
                 str(Path.home() / "AppData/Local/Programs/Inno Setup 6")):
        candidate = Path(base) / "ISCC.exe"
        if candidate.exists():
            return str(candidate)
    return None


def write_spec(icon: Path) -> Path:
    spec_path = ROOT / "build" / "anihub.spec"
    spec_path.parent.mkdir(exist_ok=True)
    content = SPEC.format(entry=str(ROOT / "packaging" / "entry.py"), entry_music=str(ROOT / "packaging" / "entry_music.py"),
                          src=str(ROOT / "src"), data=str(ROOT / "src" / "anihub" / "data"), icon=str(icon),
                          hidden=["anihub.core.lang." + p.stem for p in (ROOT / "src" / "anihub" / "core" / "lang").glob("*.py")
                                  if p.stem != "__init__"],
                          excludes=EXCLUDES)
    spec_path.write_text(content, encoding="utf-8")
    return spec_path


def main() -> None:
    from anihub import __version__

    icon = make_icon()
    spec = write_spec(icon)
    args = [sys.executable, "-m", "PyInstaller", "--noconfirm", "--clean", "--distpath", str(ROOT / "dist"),
            "--workpath", str(ROOT / "build" / "pyi"), str(spec)]
    subprocess.run(args, check=True, cwd=ROOT)
    iscc = find_iscc()
    if not iscc:
        sys.exit("Inno Setup (ISCC.exe) not found: install it with `winget install JRSoftware.InnoSetup`")
    subprocess.run([iscc, f"/DAppVersion={__version__}", str(ROOT / "packaging" / "installer.iss")], check=True, cwd=ROOT)
    print("installer:", ROOT / "dist" / f"AniHUB-Setup-{__version__}.exe")


if __name__ == "__main__":
    main()
